### PR TITLE
Swap hxproj with hxml

### PR DESCRIPTION
**Pull request by aBARICHELLO**
As discussed in #22

### CODE REVIEW

**Comment by aBARICHELLO** [comment]
Also, the Java target for the sys-server is not building. I don't know how to fix it.
```
haxelib run hxjava hxjava_build.txt --haxe-version 4005 --feature-level 1
javac "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
src/hx/ws/WebSocketServer_start_57__Fun.java:21: error: illegal character: '`'
		`this.tick();
		^
src/hx/ws/WebSocketServer_start_57__Fun.java:23: error: illegal character: '`'
		haxe.root.Sys.sleep(`this.sleepAmount);
		                    ^
src/hx/ws/WebSocketServer_start_57__Fun.java:23: error: ';' expected
		haxe.root.Sys.sleep(`this.sleepAmount);
		                     ^
src/hx/ws/WebSocketServer_start_57__Fun.java:23: error: illegal start of expression
		haxe.root.Sys.sleep(`this.sleepAmount);
		                         ^
src/hx/ws/WebSocketServer_start_57__Fun.java:23: error: ';' expected
		haxe.root.Sys.sleep(`this.sleepAmount);
		                                     ^
5 errors
Compilation error
Native compilation failed
Error: Build failed
```

**Comment by ianharrigan** [comment]
That backtick error is strange, never used to happen, so something has changed (i get the same error) - looks like a hxJava bug... i wonder if using the JVM target will work out better - ill test.

Btw, what would be the problem with keeping .hxproj _and_ .hxml? I mean, they are both perfectly usable, so why not have both (eg: i use haxe develop)

**Comment by ianharrigan** [comment]
UPDATE: so with the new jvm target (which i believe is the future of the java target) it compiles and seems to work fine... :/

**Comment by aBARICHELLO** [comment]
> Btw, what would be the problem with keeping .hxproj _and_ .hxml? I mean, they are both perfectly usable, so why not have both (eg: i use haxe develop)

I couldn't find a lot of info about .hxproj but it looks like it's an old build format. It's not even mentioned in the official docs which only provides .hxml examples.
I can re-add them to the PR if you want.

**Comment by ianharrigan** [comment]
Yeah, it might make sense to re-add then, HaxeDevelop is certainly used, although VSCode is certainly the preferred / official way now i believe.

**Comment by aBARICHELLO** [comment]
Done 👍🏼

**Comment by ianharrigan** [comment]
Nice one, thanks!

**Pull request merged**
