### PR TITLE
Usability improvements

### PR DESCRIPTION
**Pull request by Tezar**
Few tweaks needed for my use case but general enough to be beneficial for others

- haxe4 compatibiilty (just use sys.thread.Thread)
- SSL support
- correctly pass uri and host via HTTP headers
- fixed edge case in HTTP handshake handling

### CODE REVIEW

**Comment by ianharrigan** [comment]
Nice one... thanks for this!

**Comment by ianharrigan** [comment]
Ive just find some issues with this while trying to add java support... have you tried the neko server and client? It doesnt work anymore and its something (i think) to do with the new way of reading the initial http request

**Comment by ianharrigan** [comment]
Ive made some changes here: https://github.com/ianharrigan/hxWebSockets/commit/71d1bab5f1694c4cff8282a659eede38fb077f03 - what im unsure of is how it ever worked with you :)

**Comment by Tezar** [comment]
I tested only client portion on neko. 

Made few "unit tests" for buffer and it worked as expected, but looking at your changes I haven't tried splitting with multiple chunks present and already few bytes consumed. 

For the websocket URI default value, you can now remove this check. You doing it during parsing makes more sense. https://github.com/ianharrigan/hxWebSockets/blob/28eda5d4f3d2bd30802624a22d1204d2cc3f5ba3/hx/ws/WebSocket.hx#L174

Tried your changes and it didn't break anything for me

**Comment by ianharrigan** [comment]
Great... fantastic it didnt break anything! There is also java (nio) and c# support now :)

**Pull request merged**
